version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
  eb: circleci/aws-elastic-beanstalk@2.0.1
  browser-tools: circleci/browser-tools@1.2.4
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install
      - aws-cli/setup
      - eb/setup
      - browser-tools/install-chrome
      - run:
          command: npm run setup
          name: install the dependencies for both projects
      -  run:
          command: |
            google-chrome --version
          name: Check Browser installation
      - run:
          command: npm run build:api
          name: Build the API project
      - run:
          command: npm run build:frontend
          name: Build the frontend project
      - run:
          command: npm run test
          name: Test the project
      - run:
          command: npm run deploy:api
          name: deploy the API project
      - run:
          command: npm run deploy:frontend
          name: deploy the frontend project